name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          # Add any other dependencies your Sphinx project may need
          # For example, if you're using nbsphinx for Jupyter notebooks
          # pip install nbsphinx pandoc

      - name: Build Sphinx Documentation
        run: |
          # Adjust the source and build directories as necessary for your project
          sphinx-build -b html docs/ build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          # Set publish_branch to gh-pages if you want to deploy to a branch named gh-pages
          publish_branch: gh-pages
